name: Build Calculator APK

on:
  push:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk android-sdk

      - name: Install Buildozer
        run: |
          pip3 install --user buildozer cython

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android tools
        run: |
          ls $ANDROID_HOME/cmdline-tools
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0" "platforms;android-35"

      - name: Build APK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mathematical-Calculator-APK
          path: bin/*.apk

